# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: StandAloneDouyin

on:
  push:
    branches: [ "feat/actions" ]
  pull_request:
    branches: [ "feat/actions" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Setup MySql
      uses: nnhy/mysql-action@v1.0

    - name: Try connect to MySQL
      run: |
        sudo mysql -uroot -proot

    - name: start test
      run: |
        cd tests 
        bash ./start_douyin.sh
        go test ./integration
