# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: StandAloneDouyin

on:
  push:
    branches: [ "feat/actions" ]
  pull_request:
    branches: [ "feat/actions" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Set up and start MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo service mysql start

    - name: Try connect to MySQL
      run: |
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH '' BY '123456';"
        sudo mysql -uroot -p123456

    - name: start test
      run: |
        cd tests 
        bash ./start_douyin.sh
        go test ./integration
